keywords:
  - дивиденды
  - buyback
  - отчетность
  - guidance
  - прибыль
  - убыток
  - revenue
  - выручка
  - квартал
  - результаты
  - финансы
  - earnings
  - акция
  - рост
  - падение
  - инвестиции
  - маржа
  - EBITDA
  - капитализация
  - IPO
  - SPO
  - слияние
  - поглощение
  - M&A
  - сделка
  - контракт
  - партнерство
  - инвесторы
  - аналитики
  - прогноз
  - таргет
  - target
  - рекомендация
  - покупать
  - продавать
  - держать
  - аптренд
  - даунтренд
  - бычий
  - медвежий
  - bullish
  - bearish
  - волатильность
  - volatility
  - ликвидность
  - объем
  - volume
  - котировки
  - цена
  - стоимость
  - оценка
  - мультипликатор
  - P/E
  - EPS
  - дивидендная доходность
  - выкуп акций
  - байбэк
  - долг
  - кредит
  - облигации
  - bonds
  - yield
  - доходность
  - купон
  - эмиссия
  - размещение
  - листинг
  - делистинг
  - split
  - сплит
  - консолидация
  - реорганизация
  - банкротство
  - дефолт
  - санкции
  - sanctions
  - регулятор
  - ЦБ
  - Fed
  - ФРС
  - ставка
  - инфляция
  - deflation
  - рецессия
  - recession
  - кризис
  - crisis
  - индекс
  - index
  - S&P
  - Nasdaq
  - Dow
  - ММВБ
  - РТС
  - биржа
  - торги
  - сессия
  - открытие
  - закрытие
